// This file is automatically generated from your CSS. Any edits will be overwritten.
export const messageContentContainer: string;
export const messageContent: string;
export const messageImage: string;
export const messageBlank: string;
export const messageContentContent: string;
export const messageTime: string;
