// This file is automatically generated from your CSS. Any edits will be overwritten.
export const headContainer: string;
export const section2: string;
export const section3: string;
export const quoteContainer: string;
export const quote: string;
export const slogan: string;
export const redButton: string;
export const greenButton: string;
export const blankSpace: string;
