// This file is automatically generated from your CSS. Any edits will be overwritten.
export const list: string;
export const item: string;
export const itemSelected: string;
export const itemImage: string;
export const itemContent: string;
