// This file is automatically generated from your CSS. Any edits will be overwritten.
export const conversation: string;
export const conversationName: string;
export const conversationMessage: string;
export const conversationBottom: string;
export const conversationInput: string;
export const conversationButton: string;
export const conversationTop: string;
export const conversationRound: string;
export const conversationTriangle: string;
