// This file is automatically generated from your CSS. Any edits will be overwritten.
export const footer: string;
export const footerLeft: string;
export const footerLinks: string;
export const linkCategory: string;
export const categoryTitle: string;
export const legalMentions: string;
export const footerLogo: string;
export const footerLogoText: string;
export const footerLogoContent: string;
export const categoryLink: string;
