// This file is automatically generated from your CSS. Any edits will be overwritten.
export const homeNavContainer: string;
export const mainLogo: string;
export const accountLink: string;
export const homeLink: string;
export const homeLogo: string;
export const basicLink: string;
export const linkRight: string;
export const linkRightContainer: string;
export const filledLink: string;
export const logoLink: string;
