// This file is automatically generated from your CSS. Any edits will be overwritten.
export const expertComponentContainer: string;
export const expertComponentTop: string;
export const expertComponentBottom: string;
export const expertComponentBottomLeft: string;
